version: '3.1'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: clinic-service-system-db
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql
      - "./init.sql:/docker-entrypoint-initdb.d/1.sql"
volumes:
  my-db: